name: Deploy to GCE VM

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Prepare SSH (key + known_hosts)
        run: |
          mkdir -p ~/.ssh && chmod 700 ~/.ssh
          # записуємо приватний ключ із секрету (ключ БЕЗ пароля)
          cat > ~/.ssh/id_ed25519 <<'EOF'
          ${{ secrets.SSH_KEY }}
          EOF
          chmod 600 ~/.ssh/id_ed25519
          # додаємо ключ хоста, щоб не було prompt
          ssh-keyscan -p "${{ secrets.SSH_PORT || 22 }}" "${{ secrets.SSH_HOST }}" >> ~/.ssh/known_hosts
          chmod 600 ~/.ssh/known_hosts

      - name: SSH connectivity check
        run: |
          ssh -i ~/.ssh/id_ed25519 -o BatchMode=yes -o StrictHostKeyChecking=yes \
              -p ${{ secrets.SSH_PORT || 22 }} \
              ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} "echo SSH_OK && hostname && date"

      - name: Rsync code to VM
        run: |
          rsync -az --delete \
            -e "ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes -p ${{ secrets.SSH_PORT || 22 }}" \
            --exclude '.git' --exclude '.github' \
            --exclude '__pycache__' --exclude '*.pyc' \
            --exclude '.env' \
            ./lab5/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/DataBase/lab5/

      - name: Remote deploy (deps + restart)
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes -p ${{ secrets.SSH_PORT || 22 }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '~/deploy_lab5.sh'

      - name: Remote health check
        run: |
          ssh -i ~/.ssh/id_ed25519 -o StrictHostKeyChecking=yes -p ${{ secrets.SSH_PORT || 22 }} \
            ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            set -e
            for i in {1..30}; do
              code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1/health || true)
              if [ "$code" = "200" ]; then echo "Healthy"; exit 0; fi
              echo "Not ready ($i), code=$code"; sleep 2
            done
            exit 1
          '
