name: Deploy to GCE VM

on:
  push:
    branches: [ "main" ]
  workflow_dispatch: {}

jobs:
  deploy:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4

      # 1) Отримуємо host key ВМ (для known_hosts)
      - name: Scan VM host key
        id: scan
        run: |
          KH=$(ssh-keyscan -p "${{ secrets.SSH_PORT || 22 }}" "${{ secrets.SSH_HOST }}" 2>/dev/null)
          echo "known_hosts<<EOF" >> $GITHUB_OUTPUT
          echo "$KH" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      # 2) Встановлюємо SSH-ключ з паролем
      - name: Install SSH key (with passphrase)
        uses: shimataro/ssh-key-action@v2
        with:
          key: ${{ secrets.SSH_KEY }}
          passphrase: ${{ secrets.SSH_PASSPHRASE }}
          known_hosts: ${{ steps.scan.outputs.known_hosts }}

      # 3) Синхронізуємо код з локальної папки "lab5/" у "/home/<user>/DataBase/lab5/" на ВМ
      - name: Rsync code to VM
        run: |
          rsync -az --delete \
            -e "ssh -p ${{ secrets.SSH_PORT || 22 }}" \
            --exclude '.git' \
            --exclude '.github' \
            --exclude '__pycache__' \
            --exclude '*.pyc' \
            --exclude '.env' \
            ./lab5/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/home/${{ secrets.SSH_USER }}/DataBase/lab5/

      # 4) Деплой-скрипт на ВМ (ставить залежності, рестартить flask)
      - name: Remote deploy (deps + restart)
        run: |
          ssh -p ${{ secrets.SSH_PORT || 22 }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '~/deploy_lab5.sh'

      # 5) Health-check через nginx -> gunicorn
      - name: Remote health check
        run: |
          ssh -p ${{ secrets.SSH_PORT || 22 }} ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }} '
            set -e
            for i in {1..30}; do
              code=$(curl -s -o /dev/null -w "%{http_code}" http://127.0.0.1/health || true)
              if [ "$code" = "200" ]; then echo "Healthy"; exit 0; fi
              echo "Not ready ($i), code=$code"; sleep 2
            done
            exit 1
          '
